# coding: utf-8

"""
    Stats API Documentation

    Official API for Major League Baseball.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.baseball_roster import BaseballRoster  # noqa: E501
from swagger_client.rest import ApiException


class TestBaseballRoster(unittest.TestCase):
    """BaseballRoster unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaseballRoster(self):
        """Test BaseballRoster"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.baseball_roster.BaseballRoster()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
