# coding: utf-8

"""
    Stats API Documentation

    Official API for Major League Baseball.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.home_run_derby_rest_object import HomeRunDerbyRestObject  # noqa: E501
from swagger_client.rest import ApiException


class TestHomeRunDerbyRestObject(unittest.TestCase):
    """HomeRunDerbyRestObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHomeRunDerbyRestObject(self):
        """Test HomeRunDerbyRestObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.home_run_derby_rest_object.HomeRunDerbyRestObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
