# coding: utf-8

"""
    Stats API Documentation

    Official API for Major League Baseball.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.depth_chart import DepthChart  # noqa: E501
from swagger_client.rest import ApiException


class TestDepthChart(unittest.TestCase):
    """DepthChart unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDepthChart(self):
        """Test DepthChart"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.depth_chart.DepthChart()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
