# coding: utf-8

"""
    Stats API Documentation

    Official API for Major League Baseball.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.venue import Venue  # noqa: E501
from swagger_client.rest import ApiException


class TestVenue(unittest.TestCase):
    """Venue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVenue(self):
        """Test Venue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.venue.Venue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
