# coding: utf-8

"""
    Stats API Documentation

    Official API for Major League Baseball.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BaseballLineup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'requesting_user_role': 'Role',
        'away_players': 'list[BaseballPerson]',
        'home_players': 'list[BaseballPerson]',
        'hydrated_people': 'dict(str, object)',
        'user_privileges': 'list[Privilege]'
    }

    attribute_map = {
        'requesting_user_role': 'requestingUserRole',
        'away_players': 'awayPlayers',
        'home_players': 'homePlayers',
        'hydrated_people': 'hydratedPeople',
        'user_privileges': 'userPrivileges'
    }

    def __init__(self, requesting_user_role=None, away_players=None, home_players=None, hydrated_people=None, user_privileges=None):  # noqa: E501
        """BaseballLineup - a model defined in Swagger"""  # noqa: E501
        self._requesting_user_role = None
        self._away_players = None
        self._home_players = None
        self._hydrated_people = None
        self._user_privileges = None
        self.discriminator = None
        if requesting_user_role is not None:
            self.requesting_user_role = requesting_user_role
        if away_players is not None:
            self.away_players = away_players
        if home_players is not None:
            self.home_players = home_players
        if hydrated_people is not None:
            self.hydrated_people = hydrated_people
        if user_privileges is not None:
            self.user_privileges = user_privileges

    @property
    def requesting_user_role(self):
        """Gets the requesting_user_role of this BaseballLineup.  # noqa: E501


        :return: The requesting_user_role of this BaseballLineup.  # noqa: E501
        :rtype: Role
        """
        return self._requesting_user_role

    @requesting_user_role.setter
    def requesting_user_role(self, requesting_user_role):
        """Sets the requesting_user_role of this BaseballLineup.


        :param requesting_user_role: The requesting_user_role of this BaseballLineup.  # noqa: E501
        :type: Role
        """

        self._requesting_user_role = requesting_user_role

    @property
    def away_players(self):
        """Gets the away_players of this BaseballLineup.  # noqa: E501


        :return: The away_players of this BaseballLineup.  # noqa: E501
        :rtype: list[BaseballPerson]
        """
        return self._away_players

    @away_players.setter
    def away_players(self, away_players):
        """Sets the away_players of this BaseballLineup.


        :param away_players: The away_players of this BaseballLineup.  # noqa: E501
        :type: list[BaseballPerson]
        """

        self._away_players = away_players

    @property
    def home_players(self):
        """Gets the home_players of this BaseballLineup.  # noqa: E501


        :return: The home_players of this BaseballLineup.  # noqa: E501
        :rtype: list[BaseballPerson]
        """
        return self._home_players

    @home_players.setter
    def home_players(self, home_players):
        """Sets the home_players of this BaseballLineup.


        :param home_players: The home_players of this BaseballLineup.  # noqa: E501
        :type: list[BaseballPerson]
        """

        self._home_players = home_players

    @property
    def hydrated_people(self):
        """Gets the hydrated_people of this BaseballLineup.  # noqa: E501


        :return: The hydrated_people of this BaseballLineup.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._hydrated_people

    @hydrated_people.setter
    def hydrated_people(self, hydrated_people):
        """Sets the hydrated_people of this BaseballLineup.


        :param hydrated_people: The hydrated_people of this BaseballLineup.  # noqa: E501
        :type: dict(str, object)
        """

        self._hydrated_people = hydrated_people

    @property
    def user_privileges(self):
        """Gets the user_privileges of this BaseballLineup.  # noqa: E501


        :return: The user_privileges of this BaseballLineup.  # noqa: E501
        :rtype: list[Privilege]
        """
        return self._user_privileges

    @user_privileges.setter
    def user_privileges(self, user_privileges):
        """Sets the user_privileges of this BaseballLineup.


        :param user_privileges: The user_privileges of this BaseballLineup.  # noqa: E501
        :type: list[Privilege]
        """

        self._user_privileges = user_privileges

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BaseballLineup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BaseballLineup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
