# coding: utf-8

"""
    Stats API Documentation

    Official API for Major League Baseball.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EventStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start_time_tbd': 'bool',
        'detailed_state': 'str',
        'code': 'str',
        'abstract_game_state': 'str'
    }

    attribute_map = {
        'start_time_tbd': 'startTimeTBD',
        'detailed_state': 'detailedState',
        'code': 'code',
        'abstract_game_state': 'abstractGameState'
    }

    def __init__(self, start_time_tbd=None, detailed_state=None, code=None, abstract_game_state=None):  # noqa: E501
        """EventStatus - a model defined in Swagger"""  # noqa: E501
        self._start_time_tbd = None
        self._detailed_state = None
        self._code = None
        self._abstract_game_state = None
        self.discriminator = None
        if start_time_tbd is not None:
            self.start_time_tbd = start_time_tbd
        if detailed_state is not None:
            self.detailed_state = detailed_state
        if code is not None:
            self.code = code
        if abstract_game_state is not None:
            self.abstract_game_state = abstract_game_state

    @property
    def start_time_tbd(self):
        """Gets the start_time_tbd of this EventStatus.  # noqa: E501


        :return: The start_time_tbd of this EventStatus.  # noqa: E501
        :rtype: bool
        """
        return self._start_time_tbd

    @start_time_tbd.setter
    def start_time_tbd(self, start_time_tbd):
        """Sets the start_time_tbd of this EventStatus.


        :param start_time_tbd: The start_time_tbd of this EventStatus.  # noqa: E501
        :type: bool
        """

        self._start_time_tbd = start_time_tbd

    @property
    def detailed_state(self):
        """Gets the detailed_state of this EventStatus.  # noqa: E501


        :return: The detailed_state of this EventStatus.  # noqa: E501
        :rtype: str
        """
        return self._detailed_state

    @detailed_state.setter
    def detailed_state(self, detailed_state):
        """Sets the detailed_state of this EventStatus.


        :param detailed_state: The detailed_state of this EventStatus.  # noqa: E501
        :type: str
        """

        self._detailed_state = detailed_state

    @property
    def code(self):
        """Gets the code of this EventStatus.  # noqa: E501


        :return: The code of this EventStatus.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this EventStatus.


        :param code: The code of this EventStatus.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def abstract_game_state(self):
        """Gets the abstract_game_state of this EventStatus.  # noqa: E501


        :return: The abstract_game_state of this EventStatus.  # noqa: E501
        :rtype: str
        """
        return self._abstract_game_state

    @abstract_game_state.setter
    def abstract_game_state(self, abstract_game_state):
        """Sets the abstract_game_state of this EventStatus.


        :param abstract_game_state: The abstract_game_state of this EventStatus.  # noqa: E501
        :type: str
        """

        self._abstract_game_state = abstract_game_state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EventStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
