# coding: utf-8

"""
    Stats API Documentation

    Official API for Major League Baseball.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HighLowStatEnum(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AT_BATS = "AT_BATS"
    TOTAL_PLATE_APPEARANCES = "TOTAL_PLATE_APPEARANCES"
    RUNS = "RUNS"
    RUNS_BATTED_IN = "RUNS_BATTED_IN"
    HOME_TEAM_RUNS = "HOME_TEAM_RUNS"
    AWAY_TEAM_RUNS = "AWAY_TEAM_RUNS"
    HITS = "HITS"
    HITS_RISP = "HITS_RISP"
    HOME_TEAM_HITS = "HOME_TEAM_HITS"
    AWAY_TEAM_HITS = "AWAY_TEAM_HITS"
    TOTAL_BASES = "TOTAL_BASES"
    DOUBLES = "DOUBLES"
    TRIPLES = "TRIPLES"
    HOME_RUNS = "HOME_RUNS"
    EXTRA_BASE_HITS = "EXTRA_BASE_HITS"
    WALKS = "WALKS"
    STRIKEOUTS = "STRIKEOUTS"
    STOLEN_BASES = "STOLEN_BASES"
    CAUGHT_STEALING = "CAUGHT_STEALING"
    SACRIFICE_FLIES = "SACRIFICE_FLIES"
    SACRIFICE_BUNTS = "SACRIFICE_BUNTS"
    HIT_BY_PITCHES = "HIT_BY_PITCHES"
    LEFT_ON_BASE = "LEFT_ON_BASE"
    GROUND_INTO_DOUBLE_PLAYS = "GROUND_INTO_DOUBLE_PLAYS"
    STRIKES = "STRIKES"
    PITCHES = "PITCHES"
    BALKS = "BALKS"
    INNINGS_PITCHED = "INNINGS_PITCHED"
    ERRORS = "ERRORS"
    HOME_TEAM_ERRORS = "HOME_TEAM_ERRORS"
    AWAY_TEAM_ERRORS = "AWAY_TEAM_ERRORS"
    CHANCES = "CHANCES"
    PUT_OUTS = "PUT_OUTS"
    ASSISTS = "ASSISTS"
    DOUBLE_PLAYS = "DOUBLE_PLAYS"
    ATTENDANCE = "ATTENDANCE"
    GAME_TIME = "GAME_TIME"
    DELAY_TIME = "DELAY_TIME"
    LONGEST = "LONGEST"
    SHORTEST = "SHORTEST"
    INNING = "INNING"
    WIN_STREAK = "WIN_STREAK"
    LOSS_STREAK = "LOSS_STREAK"
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
    }

    attribute_map = {
    }

    def __init__(self):  # noqa: E501
        """HighLowStatEnum - a model defined in Swagger"""  # noqa: E501
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HighLowStatEnum, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HighLowStatEnum):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
