# coding: utf-8

"""
    Stats API Documentation

    Official API for Major League Baseball.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Image(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'images': 'dict(str, str)',
        'caption': 'str',
        'image_type': 'ImageTypeEnum',
        'url': 'str',
        'image_type_as_string': 'str'
    }

    attribute_map = {
        'images': 'images',
        'caption': 'caption',
        'image_type': 'imageType',
        'url': 'url',
        'image_type_as_string': 'imageTypeAsString'
    }

    def __init__(self, images=None, caption=None, image_type=None, url=None, image_type_as_string=None):  # noqa: E501
        """Image - a model defined in Swagger"""  # noqa: E501
        self._images = None
        self._caption = None
        self._image_type = None
        self._url = None
        self._image_type_as_string = None
        self.discriminator = None
        if images is not None:
            self.images = images
        if caption is not None:
            self.caption = caption
        if image_type is not None:
            self.image_type = image_type
        if url is not None:
            self.url = url
        if image_type_as_string is not None:
            self.image_type_as_string = image_type_as_string

    @property
    def images(self):
        """Gets the images of this Image.  # noqa: E501


        :return: The images of this Image.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._images

    @images.setter
    def images(self, images):
        """Sets the images of this Image.


        :param images: The images of this Image.  # noqa: E501
        :type: dict(str, str)
        """

        self._images = images

    @property
    def caption(self):
        """Gets the caption of this Image.  # noqa: E501


        :return: The caption of this Image.  # noqa: E501
        :rtype: str
        """
        return self._caption

    @caption.setter
    def caption(self, caption):
        """Sets the caption of this Image.


        :param caption: The caption of this Image.  # noqa: E501
        :type: str
        """

        self._caption = caption

    @property
    def image_type(self):
        """Gets the image_type of this Image.  # noqa: E501


        :return: The image_type of this Image.  # noqa: E501
        :rtype: ImageTypeEnum
        """
        return self._image_type

    @image_type.setter
    def image_type(self, image_type):
        """Sets the image_type of this Image.


        :param image_type: The image_type of this Image.  # noqa: E501
        :type: ImageTypeEnum
        """

        self._image_type = image_type

    @property
    def url(self):
        """Gets the url of this Image.  # noqa: E501


        :return: The url of this Image.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this Image.


        :param url: The url of this Image.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def image_type_as_string(self):
        """Gets the image_type_as_string of this Image.  # noqa: E501


        :return: The image_type_as_string of this Image.  # noqa: E501
        :rtype: str
        """
        return self._image_type_as_string

    @image_type_as_string.setter
    def image_type_as_string(self, image_type_as_string):
        """Sets the image_type_as_string of this Image.


        :param image_type_as_string: The image_type_as_string of this Image.  # noqa: E501
        :type: str
        """

        self._image_type_as_string = image_type_as_string

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Image, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Image):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
