# coding: utf-8

"""
    Stats API Documentation

    Official API for Major League Baseball.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InningPlay(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'copyright': 'str',
        'start_index': 'int',
        'end_index': 'int',
        'top': 'list[int]',
        'bottom': 'list[int]',
        'hits': 'InningHitWrap'
    }

    attribute_map = {
        'copyright': 'copyright',
        'start_index': 'startIndex',
        'end_index': 'endIndex',
        'top': 'top',
        'bottom': 'bottom',
        'hits': 'hits'
    }

    def __init__(self, copyright=None, start_index=None, end_index=None, top=None, bottom=None, hits=None):  # noqa: E501
        """InningPlay - a model defined in Swagger"""  # noqa: E501
        self._copyright = None
        self._start_index = None
        self._end_index = None
        self._top = None
        self._bottom = None
        self._hits = None
        self.discriminator = None
        if copyright is not None:
            self.copyright = copyright
        if start_index is not None:
            self.start_index = start_index
        if end_index is not None:
            self.end_index = end_index
        if top is not None:
            self.top = top
        if bottom is not None:
            self.bottom = bottom
        if hits is not None:
            self.hits = hits

    @property
    def copyright(self):
        """Gets the copyright of this InningPlay.  # noqa: E501


        :return: The copyright of this InningPlay.  # noqa: E501
        :rtype: str
        """
        return self._copyright

    @copyright.setter
    def copyright(self, copyright):
        """Sets the copyright of this InningPlay.


        :param copyright: The copyright of this InningPlay.  # noqa: E501
        :type: str
        """

        self._copyright = copyright

    @property
    def start_index(self):
        """Gets the start_index of this InningPlay.  # noqa: E501


        :return: The start_index of this InningPlay.  # noqa: E501
        :rtype: int
        """
        return self._start_index

    @start_index.setter
    def start_index(self, start_index):
        """Sets the start_index of this InningPlay.


        :param start_index: The start_index of this InningPlay.  # noqa: E501
        :type: int
        """

        self._start_index = start_index

    @property
    def end_index(self):
        """Gets the end_index of this InningPlay.  # noqa: E501


        :return: The end_index of this InningPlay.  # noqa: E501
        :rtype: int
        """
        return self._end_index

    @end_index.setter
    def end_index(self, end_index):
        """Sets the end_index of this InningPlay.


        :param end_index: The end_index of this InningPlay.  # noqa: E501
        :type: int
        """

        self._end_index = end_index

    @property
    def top(self):
        """Gets the top of this InningPlay.  # noqa: E501


        :return: The top of this InningPlay.  # noqa: E501
        :rtype: list[int]
        """
        return self._top

    @top.setter
    def top(self, top):
        """Sets the top of this InningPlay.


        :param top: The top of this InningPlay.  # noqa: E501
        :type: list[int]
        """

        self._top = top

    @property
    def bottom(self):
        """Gets the bottom of this InningPlay.  # noqa: E501


        :return: The bottom of this InningPlay.  # noqa: E501
        :rtype: list[int]
        """
        return self._bottom

    @bottom.setter
    def bottom(self, bottom):
        """Sets the bottom of this InningPlay.


        :param bottom: The bottom of this InningPlay.  # noqa: E501
        :type: list[int]
        """

        self._bottom = bottom

    @property
    def hits(self):
        """Gets the hits of this InningPlay.  # noqa: E501


        :return: The hits of this InningPlay.  # noqa: E501
        :rtype: InningHitWrap
        """
        return self._hits

    @hits.setter
    def hits(self, hits):
        """Sets the hits of this InningPlay.


        :param hits: The hits of this InningPlay.  # noqa: E501
        :type: InningHitWrap
        """

        self._hits = hits

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InningPlay, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InningPlay):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
