# coding: utf-8

"""
    Stats API Documentation

    Official API for Major League Baseball.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MilestoneAchievementType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'achievement_type_id': 'int',
        'achievement_type_code': 'str',
        'achievement_type_desc': 'str',
        'achievement_type_text': 'str'
    }

    attribute_map = {
        'achievement_type_id': 'achievementTypeId',
        'achievement_type_code': 'achievementTypeCode',
        'achievement_type_desc': 'achievementTypeDesc',
        'achievement_type_text': 'achievementTypeText'
    }

    def __init__(self, achievement_type_id=None, achievement_type_code=None, achievement_type_desc=None, achievement_type_text=None):  # noqa: E501
        """MilestoneAchievementType - a model defined in Swagger"""  # noqa: E501
        self._achievement_type_id = None
        self._achievement_type_code = None
        self._achievement_type_desc = None
        self._achievement_type_text = None
        self.discriminator = None
        if achievement_type_id is not None:
            self.achievement_type_id = achievement_type_id
        if achievement_type_code is not None:
            self.achievement_type_code = achievement_type_code
        if achievement_type_desc is not None:
            self.achievement_type_desc = achievement_type_desc
        if achievement_type_text is not None:
            self.achievement_type_text = achievement_type_text

    @property
    def achievement_type_id(self):
        """Gets the achievement_type_id of this MilestoneAchievementType.  # noqa: E501


        :return: The achievement_type_id of this MilestoneAchievementType.  # noqa: E501
        :rtype: int
        """
        return self._achievement_type_id

    @achievement_type_id.setter
    def achievement_type_id(self, achievement_type_id):
        """Sets the achievement_type_id of this MilestoneAchievementType.


        :param achievement_type_id: The achievement_type_id of this MilestoneAchievementType.  # noqa: E501
        :type: int
        """

        self._achievement_type_id = achievement_type_id

    @property
    def achievement_type_code(self):
        """Gets the achievement_type_code of this MilestoneAchievementType.  # noqa: E501


        :return: The achievement_type_code of this MilestoneAchievementType.  # noqa: E501
        :rtype: str
        """
        return self._achievement_type_code

    @achievement_type_code.setter
    def achievement_type_code(self, achievement_type_code):
        """Sets the achievement_type_code of this MilestoneAchievementType.


        :param achievement_type_code: The achievement_type_code of this MilestoneAchievementType.  # noqa: E501
        :type: str
        """

        self._achievement_type_code = achievement_type_code

    @property
    def achievement_type_desc(self):
        """Gets the achievement_type_desc of this MilestoneAchievementType.  # noqa: E501


        :return: The achievement_type_desc of this MilestoneAchievementType.  # noqa: E501
        :rtype: str
        """
        return self._achievement_type_desc

    @achievement_type_desc.setter
    def achievement_type_desc(self, achievement_type_desc):
        """Sets the achievement_type_desc of this MilestoneAchievementType.


        :param achievement_type_desc: The achievement_type_desc of this MilestoneAchievementType.  # noqa: E501
        :type: str
        """

        self._achievement_type_desc = achievement_type_desc

    @property
    def achievement_type_text(self):
        """Gets the achievement_type_text of this MilestoneAchievementType.  # noqa: E501


        :return: The achievement_type_text of this MilestoneAchievementType.  # noqa: E501
        :rtype: str
        """
        return self._achievement_type_text

    @achievement_type_text.setter
    def achievement_type_text(self, achievement_type_text):
        """Sets the achievement_type_text of this MilestoneAchievementType.


        :param achievement_type_text: The achievement_type_text of this MilestoneAchievementType.  # noqa: E501
        :type: str
        """

        self._achievement_type_text = achievement_type_text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MilestoneAchievementType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MilestoneAchievementType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
