# coding: utf-8

"""
    Stats API Documentation

    Official API for Major League Baseball.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PitchSegmentRestObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'copyright': 'str',
        'last_measured_data': 'StartEndDataRestObject',
        'release_data': 'ReleaseDataRestObject',
        'trajectory_data': 'PitchTrajectoryDataRestObject'
    }

    attribute_map = {
        'copyright': 'copyright',
        'last_measured_data': 'lastMeasuredData',
        'release_data': 'releaseData',
        'trajectory_data': 'trajectoryData'
    }

    def __init__(self, copyright=None, last_measured_data=None, release_data=None, trajectory_data=None):  # noqa: E501
        """PitchSegmentRestObject - a model defined in Swagger"""  # noqa: E501
        self._copyright = None
        self._last_measured_data = None
        self._release_data = None
        self._trajectory_data = None
        self.discriminator = None
        if copyright is not None:
            self.copyright = copyright
        if last_measured_data is not None:
            self.last_measured_data = last_measured_data
        if release_data is not None:
            self.release_data = release_data
        if trajectory_data is not None:
            self.trajectory_data = trajectory_data

    @property
    def copyright(self):
        """Gets the copyright of this PitchSegmentRestObject.  # noqa: E501


        :return: The copyright of this PitchSegmentRestObject.  # noqa: E501
        :rtype: str
        """
        return self._copyright

    @copyright.setter
    def copyright(self, copyright):
        """Sets the copyright of this PitchSegmentRestObject.


        :param copyright: The copyright of this PitchSegmentRestObject.  # noqa: E501
        :type: str
        """

        self._copyright = copyright

    @property
    def last_measured_data(self):
        """Gets the last_measured_data of this PitchSegmentRestObject.  # noqa: E501


        :return: The last_measured_data of this PitchSegmentRestObject.  # noqa: E501
        :rtype: StartEndDataRestObject
        """
        return self._last_measured_data

    @last_measured_data.setter
    def last_measured_data(self, last_measured_data):
        """Sets the last_measured_data of this PitchSegmentRestObject.


        :param last_measured_data: The last_measured_data of this PitchSegmentRestObject.  # noqa: E501
        :type: StartEndDataRestObject
        """

        self._last_measured_data = last_measured_data

    @property
    def release_data(self):
        """Gets the release_data of this PitchSegmentRestObject.  # noqa: E501


        :return: The release_data of this PitchSegmentRestObject.  # noqa: E501
        :rtype: ReleaseDataRestObject
        """
        return self._release_data

    @release_data.setter
    def release_data(self, release_data):
        """Sets the release_data of this PitchSegmentRestObject.


        :param release_data: The release_data of this PitchSegmentRestObject.  # noqa: E501
        :type: ReleaseDataRestObject
        """

        self._release_data = release_data

    @property
    def trajectory_data(self):
        """Gets the trajectory_data of this PitchSegmentRestObject.  # noqa: E501


        :return: The trajectory_data of this PitchSegmentRestObject.  # noqa: E501
        :rtype: PitchTrajectoryDataRestObject
        """
        return self._trajectory_data

    @trajectory_data.setter
    def trajectory_data(self, trajectory_data):
        """Sets the trajectory_data of this PitchSegmentRestObject.


        :param trajectory_data: The trajectory_data of this PitchSegmentRestObject.  # noqa: E501
        :type: PitchTrajectoryDataRestObject
        """

        self._trajectory_data = trajectory_data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PitchSegmentRestObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PitchSegmentRestObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
