# coding: utf-8

"""
    Stats API Documentation

    Official API for Major League Baseball.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RunnerMovement(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'copyright': 'str',
        'movement': 'Movement',
        'details': 'Details',
        'credits': 'list[PlayCreditRestObject]'
    }

    attribute_map = {
        'copyright': 'copyright',
        'movement': 'movement',
        'details': 'details',
        'credits': 'credits'
    }

    def __init__(self, copyright=None, movement=None, details=None, credits=None):  # noqa: E501
        """RunnerMovement - a model defined in Swagger"""  # noqa: E501
        self._copyright = None
        self._movement = None
        self._details = None
        self._credits = None
        self.discriminator = None
        if copyright is not None:
            self.copyright = copyright
        if movement is not None:
            self.movement = movement
        if details is not None:
            self.details = details
        if credits is not None:
            self.credits = credits

    @property
    def copyright(self):
        """Gets the copyright of this RunnerMovement.  # noqa: E501


        :return: The copyright of this RunnerMovement.  # noqa: E501
        :rtype: str
        """
        return self._copyright

    @copyright.setter
    def copyright(self, copyright):
        """Sets the copyright of this RunnerMovement.


        :param copyright: The copyright of this RunnerMovement.  # noqa: E501
        :type: str
        """

        self._copyright = copyright

    @property
    def movement(self):
        """Gets the movement of this RunnerMovement.  # noqa: E501


        :return: The movement of this RunnerMovement.  # noqa: E501
        :rtype: Movement
        """
        return self._movement

    @movement.setter
    def movement(self, movement):
        """Sets the movement of this RunnerMovement.


        :param movement: The movement of this RunnerMovement.  # noqa: E501
        :type: Movement
        """

        self._movement = movement

    @property
    def details(self):
        """Gets the details of this RunnerMovement.  # noqa: E501


        :return: The details of this RunnerMovement.  # noqa: E501
        :rtype: Details
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this RunnerMovement.


        :param details: The details of this RunnerMovement.  # noqa: E501
        :type: Details
        """

        self._details = details

    @property
    def credits(self):
        """Gets the credits of this RunnerMovement.  # noqa: E501


        :return: The credits of this RunnerMovement.  # noqa: E501
        :rtype: list[PlayCreditRestObject]
        """
        return self._credits

    @credits.setter
    def credits(self, credits):
        """Sets the credits of this RunnerMovement.


        :param credits: The credits of this RunnerMovement.  # noqa: E501
        :type: list[PlayCreditRestObject]
        """

        self._credits = credits

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RunnerMovement, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RunnerMovement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
