# coding: utf-8

"""
    Stats API Documentation

    Official API for Major League Baseball.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ScheduleRestObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'copyright': 'str',
        'hydrations': 'list[str]',
        'total_items': 'int',
        'total_events': 'int',
        'total_games': 'int',
        'total_games_in_progress': 'int',
        'wait': 'int',
        'dates': 'list[ScheduleDateRestObject]'
    }

    attribute_map = {
        'copyright': 'copyright',
        'hydrations': 'hydrations',
        'total_items': 'totalItems',
        'total_events': 'totalEvents',
        'total_games': 'totalGames',
        'total_games_in_progress': 'totalGamesInProgress',
        'wait': 'wait',
        'dates': 'dates'
    }

    def __init__(self, copyright=None, hydrations=None, total_items=None, total_events=None, total_games=None, total_games_in_progress=None, wait=None, dates=None):  # noqa: E501
        """ScheduleRestObject - a model defined in Swagger"""  # noqa: E501
        self._copyright = None
        self._hydrations = None
        self._total_items = None
        self._total_events = None
        self._total_games = None
        self._total_games_in_progress = None
        self._wait = None
        self._dates = None
        self.discriminator = None
        if copyright is not None:
            self.copyright = copyright
        if hydrations is not None:
            self.hydrations = hydrations
        if total_items is not None:
            self.total_items = total_items
        if total_events is not None:
            self.total_events = total_events
        if total_games is not None:
            self.total_games = total_games
        if total_games_in_progress is not None:
            self.total_games_in_progress = total_games_in_progress
        if wait is not None:
            self.wait = wait
        if dates is not None:
            self.dates = dates

    @property
    def copyright(self):
        """Gets the copyright of this ScheduleRestObject.  # noqa: E501


        :return: The copyright of this ScheduleRestObject.  # noqa: E501
        :rtype: str
        """
        return self._copyright

    @copyright.setter
    def copyright(self, copyright):
        """Sets the copyright of this ScheduleRestObject.


        :param copyright: The copyright of this ScheduleRestObject.  # noqa: E501
        :type: str
        """

        self._copyright = copyright

    @property
    def hydrations(self):
        """Gets the hydrations of this ScheduleRestObject.  # noqa: E501


        :return: The hydrations of this ScheduleRestObject.  # noqa: E501
        :rtype: list[str]
        """
        return self._hydrations

    @hydrations.setter
    def hydrations(self, hydrations):
        """Sets the hydrations of this ScheduleRestObject.


        :param hydrations: The hydrations of this ScheduleRestObject.  # noqa: E501
        :type: list[str]
        """

        self._hydrations = hydrations

    @property
    def total_items(self):
        """Gets the total_items of this ScheduleRestObject.  # noqa: E501


        :return: The total_items of this ScheduleRestObject.  # noqa: E501
        :rtype: int
        """
        return self._total_items

    @total_items.setter
    def total_items(self, total_items):
        """Sets the total_items of this ScheduleRestObject.


        :param total_items: The total_items of this ScheduleRestObject.  # noqa: E501
        :type: int
        """

        self._total_items = total_items

    @property
    def total_events(self):
        """Gets the total_events of this ScheduleRestObject.  # noqa: E501


        :return: The total_events of this ScheduleRestObject.  # noqa: E501
        :rtype: int
        """
        return self._total_events

    @total_events.setter
    def total_events(self, total_events):
        """Sets the total_events of this ScheduleRestObject.


        :param total_events: The total_events of this ScheduleRestObject.  # noqa: E501
        :type: int
        """

        self._total_events = total_events

    @property
    def total_games(self):
        """Gets the total_games of this ScheduleRestObject.  # noqa: E501


        :return: The total_games of this ScheduleRestObject.  # noqa: E501
        :rtype: int
        """
        return self._total_games

    @total_games.setter
    def total_games(self, total_games):
        """Sets the total_games of this ScheduleRestObject.


        :param total_games: The total_games of this ScheduleRestObject.  # noqa: E501
        :type: int
        """

        self._total_games = total_games

    @property
    def total_games_in_progress(self):
        """Gets the total_games_in_progress of this ScheduleRestObject.  # noqa: E501


        :return: The total_games_in_progress of this ScheduleRestObject.  # noqa: E501
        :rtype: int
        """
        return self._total_games_in_progress

    @total_games_in_progress.setter
    def total_games_in_progress(self, total_games_in_progress):
        """Sets the total_games_in_progress of this ScheduleRestObject.


        :param total_games_in_progress: The total_games_in_progress of this ScheduleRestObject.  # noqa: E501
        :type: int
        """

        self._total_games_in_progress = total_games_in_progress

    @property
    def wait(self):
        """Gets the wait of this ScheduleRestObject.  # noqa: E501


        :return: The wait of this ScheduleRestObject.  # noqa: E501
        :rtype: int
        """
        return self._wait

    @wait.setter
    def wait(self, wait):
        """Sets the wait of this ScheduleRestObject.


        :param wait: The wait of this ScheduleRestObject.  # noqa: E501
        :type: int
        """

        self._wait = wait

    @property
    def dates(self):
        """Gets the dates of this ScheduleRestObject.  # noqa: E501


        :return: The dates of this ScheduleRestObject.  # noqa: E501
        :rtype: list[ScheduleDateRestObject]
        """
        return self._dates

    @dates.setter
    def dates(self, dates):
        """Sets the dates of this ScheduleRestObject.


        :param dates: The dates of this ScheduleRestObject.  # noqa: E501
        :type: list[ScheduleDateRestObject]
        """

        self._dates = dates

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ScheduleRestObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScheduleRestObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
