# coding: utf-8

"""
    Stats API Documentation

    Official API for Major League Baseball.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Weather(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'weather_condition': 'str',
        'temperature': 'str',
        'wind': 'str'
    }

    attribute_map = {
        'weather_condition': 'weatherCondition',
        'temperature': 'temperature',
        'wind': 'wind'
    }

    def __init__(self, weather_condition=None, temperature=None, wind=None):  # noqa: E501
        """Weather - a model defined in Swagger"""  # noqa: E501
        self._weather_condition = None
        self._temperature = None
        self._wind = None
        self.discriminator = None
        if weather_condition is not None:
            self.weather_condition = weather_condition
        if temperature is not None:
            self.temperature = temperature
        if wind is not None:
            self.wind = wind

    @property
    def weather_condition(self):
        """Gets the weather_condition of this Weather.  # noqa: E501


        :return: The weather_condition of this Weather.  # noqa: E501
        :rtype: str
        """
        return self._weather_condition

    @weather_condition.setter
    def weather_condition(self, weather_condition):
        """Sets the weather_condition of this Weather.


        :param weather_condition: The weather_condition of this Weather.  # noqa: E501
        :type: str
        """

        self._weather_condition = weather_condition

    @property
    def temperature(self):
        """Gets the temperature of this Weather.  # noqa: E501


        :return: The temperature of this Weather.  # noqa: E501
        :rtype: str
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature):
        """Sets the temperature of this Weather.


        :param temperature: The temperature of this Weather.  # noqa: E501
        :type: str
        """

        self._temperature = temperature

    @property
    def wind(self):
        """Gets the wind of this Weather.  # noqa: E501


        :return: The wind of this Weather.  # noqa: E501
        :rtype: str
        """
        return self._wind

    @wind.setter
    def wind(self, wind):
        """Sets the wind of this Weather.


        :param wind: The wind of this Weather.  # noqa: E501
        :type: str
        """

        self._wind = wind

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Weather, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Weather):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
